language: python
sudo: false
python:
- 2.7
- 3.3
- 3.4
- 3.5
- pypy
cache: pip
install:
- pip install --cache-dir $HOME/.cache/pip pytest pytest-cov coveralls flake8 six blinker pytest-django
- pip install --cache-dir $HOME/.cache/pip -e .[django]
- python setup.py develop
script:
- py.test --cov=graphene
- flake8
after_success:
- coveralls
