language: python
sudo: false
python:
- 2.7
- 3.3
- 3.4
- 3.5
- pypy
install:
- pip install pytest pytest-cov coveralls flake8 six blinker
# - pip install -e .[django]  # TODO: Commented until graphqllib is in pypi
- pip install Django>=1.8.0 pytest-django singledispatch>=3.4.0.3
- pip install git+https://github.com/dittos/graphqllib.git # Last version of graphqllib
- pip install graphql-relay
- python setup.py develop
script:
- py.test --cov=graphene
# - flake8
after_success:
- coveralls
